services:
  solution-archive-service:
    image: ghcr.io/${IMAGE_NAME}:latest
    container_name: solution-archive-service-reshala
    ports:
      - "8185:8185"
    environment:
      - SERVER_PORT=8185
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_ENABLED=false

      # Database
      - DB_URL=jdbc:postgresql://postgres-reshala:5432/suluton_archive_db
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver


      # RabbitMQ
      - RABBIT_HOST=rabbitmq-reshala
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=${RMQ_USER}
      - RABBIT_PASSWORD=${RMQ_PASS}
      - RABBIT_VHOST=solution-service

      # MinIO
      - MINIO_URL=http://minio-reshala:9000
      - MINIO_ACCESS-KEY=${MINIO_USER}
      - MINIO_SECRET-KEY=${MINIO_PASS}
      - MINIO_TEMP_BUCKET=${MINIO_TEMP_BUCKET}
      - MINIO_DATASET_BUCKET=${MINIO_DATASET_BUCKET}

      # Внешние сервисы (имена контейнеров в reshala-net)
      - LATEXOCR_URL=http://ocr-web-reshala:8183
      - CASENGINE_URL=http://cas-web-reshala:8184

    networks:
      - reshala-net
    restart: unless-stopped

networks:
  reshala-net:
    external: true